version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: fixithub
    container_name: fixithub-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
      - "5173:5173"
    networks:
      - fixithub

  db:
    image: "mysql/mysql-server:8.0"
    container_name: fixithub-db
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: "${DB_USERNAME}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - fixithub

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - fixithub

  nginx:
    image: nginx:alpine
    container_name: fixithub-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - fixithub

networks:
  fixithub:
    driver: bridge
